var messengerPageToken = process.env.MESSENGER_TOKEN || 'EAABvEAKqyv4BACf3aep0kMGFZBNZB2Dp3hxERYafbTUlZCLQDFDlwoyZBFizuTGGTBQY9qZAUc52mwEHGXpSJNAUPfkbkooFvGZBBWrdLOGIbEFS9gecHj7X8Xrd8hPtmoZCZBzTQBZBkn2YA4KYfnpqfFLZBmuucSo9iNioKtHuUG7AZDZD';

module.exports = {
  messengerPageToken: messengerPageToken
};
